flow package require MemGen
flow run /MemGen/MemoryGenerator_BuildLib {
VENDOR           *
RTLTOOL          DesignCompiler
TECHNOLOGY       *
LIBRARY          sram_256_128
MODULE           sram_256_128
OUTPUT_DIR       /home/users/sophliu/ee272/ee272-hw5/temp
FILES {
  { FILENAME /home/users/sophliu/ee272/ee272-hw5/temp/sram_256_128.v FILETYPE Verilog MODELTYPE generic PARSE 1 PATHTYPE copy STATICFILE 1 VHDL_LIB_MAPS work }
}
VHDLARRAYPATH    {}
WRITEDELAY       0.1
INITDELAY        1
READDELAY        0.1
VERILOGARRAYPATH {}
INPUTDELAY       0.01
TIMEUNIT         1ns
WIDTH            128
AREA             0
RDWRRESOLUTION   UNKNOWN
WRITELATENCY     1
READLATENCY      1
DEPTH            32768
PARAMETERS {
  { PARAMETER WRAPPER_DEPTH     TYPE hdl IGNORE 1 MIN {} MAX {} DEFAULT 32768 }
  { PARAMETER WRAPPER_WIDTH     TYPE hdl IGNORE 0 MIN {} MAX {} DEFAULT 128   }
  { PARAMETER WRAPPER_ADDR_BITS TYPE hdl IGNORE 0 MIN {} MAX {} DEFAULT 0     }
  { PARAMETER SRAM_DEPTH        TYPE hdl IGNORE 1 MIN {} MAX {} DEFAULT 0     }
  { PARAMETER SRAM_WIDTH        TYPE hdl IGNORE 1 MIN {} MAX {} DEFAULT 0     }
  { PARAMETER SRAM_ADDR_BITS    TYPE hdl IGNORE 1 MIN {} MAX {} DEFAULT 0     }
  { PARAMETER num_inst_depth    TYPE hdl IGNORE 1 MIN {} MAX {} DEFAULT 0     }
  { PARAMETER num_inst_width    TYPE hdl IGNORE 1 MIN {} MAX {} DEFAULT 0     }
}
PORTS {
  { NAME port_0 MODE ReadWrite }
}
PINMAPS {
  { PHYPIN clk  LOGPIN CLOCK        DIRECTION in  WIDTH 1.0               PHASE 1  DEFAULT {} PORTS port_0 }
  { PHYPIN csb  LOGPIN CHIP_SELECT  DIRECTION in  WIDTH 1.0               PHASE 0  DEFAULT {} PORTS {}     }
  { PHYPIN web  LOGPIN WRITE_ENABLE DIRECTION in  WIDTH 1.0               PHASE 0  DEFAULT {} PORTS port_0 }
  { PHYPIN addr LOGPIN ADDRESS      DIRECTION in  WIDTH WRAPPER_ADDR_BITS PHASE {} DEFAULT {} PORTS port_0 }
  { PHYPIN din  LOGPIN DATA_IN      DIRECTION in  WIDTH WRAPPER_WIDTH     PHASE {} DEFAULT {} PORTS port_0 }
  { PHYPIN dout LOGPIN DATA_OUT     DIRECTION out WIDTH WRAPPER_WIDTH     PHASE {} DEFAULT {} PORTS port_0 }
}

}
